addQuestions([
  {
    q: "What is the most common mechanism by which ionizing radiation (x-rays or gamma rays) damages cells?",
    choices: ["Direct ionization, where radiation directly cleaves DNA strands", "Indirect ionization, where absorbed radiation produces fast-moving electrons that generate free radicals interacting with critical cell components", "Thermal injury from heat generated by the radiation beam", "Direct disruption of the cell membrane's lipid bilayer"],
    correct: 1,
    explain: "Indirect ionization is the most common mechanism: x-rays or gamma rays are absorbed into tissue and give up energy by producing fast-moving electrons, which generate free radicals that interact with critical cell components, ultimately destroying nuclear DNA."
  },
  {
    q: "Which cells are preferentially injured by radiation therapy — providing the rationale for its selective effect on tumors?",
    choices: ["Slowly proliferating, well-differentiated cells", "Permanent cells such as neurons and cardiac myocytes", "Rapidly proliferating, poorly differentiated cells", "Cells that are not undergoing any mitotic activity"],
    correct: 2,
    explain: "Rapidly proliferating and poorly differentiated cells are more likely to be injured by radiation therapy than slowly proliferating cells, since radiation-induced DNA damage causes cell death upon replication — this is the basis for radiation's selective effect on tumor tissue."
  }
]);
